services:
  pgvector:
    image: 'postgres:17-alpine'
    container_name: 'social-posgres'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=mohbalor'
      - 'POSTGRES_PASSWORD=secret'
      - 'PGTZ=UTC'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '25432:5432'
    volumes:
      - social_data:/var/lib/postgresql/data  # Volume to persist data

  redis:
    image: 'redis:latest'
    container_name: 'social-redis'
    ports:
      - "16379:6379"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - '9090:8080'
    environment:
      - KEYCLOAK_ADMIN=mohbalor
      - KEYCLOAK_ADMIN_PASSWORD=secret
    volumes:
      - ./backend/keycloak-config/grad-proj-realm-export.json:/opt/keycloak/data/import/realm.json
    command:
      - "start-dev"
      - "--import-realm"

volumes:
  social_data: # Define the volume
    driver: local
