services:
  pgvector:
    image: 'pgvector/pgvector:pg17'
    container_name: 'social-container'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=mohbalor'
      - PGTZ=UTC
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '25432:5432'
    volumes:
      - social_data:/var/lib/postgresql/data  # Volume to persist data

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - '9090:8080'
    environment:
      - KEYCLOAK_ADMIN=mohbalor
      - KEYCLOAK_ADMIN_PASSWORD=secret
    command:
      - "start-dev"

volumes:
  social_data: # Define the volume
    driver: local
