/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */
export interface ChatResponse {
  chatId: number;
  name?: string;
  chatPicture: string; // Base64 encoded
  lastMessage?: string;
  lastMessageTime?: string;
  onlineRecipientsNumber?: number; // fix here!
  unreadCount: number;
  isPinned: boolean;
  isMuted: boolean;
  isDeleted: boolean;
}


