/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ChatResponse {
  chatId: string;
  chatName?: string;
  chatPicture: string;
  lastMessage?: string;
  lastMessageTime?: string;
  recipientOnline?: boolean;
  unreadCount?: number;
}
