/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserAvatar } from "../../models/ProfileResponseDto";

export interface MessageResponse {
  content?: string;
  sentAt: string;
  messageId: number;
  messageStatus: MessageStatus,
  parentMessageId: number;
  senderAvatar: UserAvatar;
  media: string;
  messageType: MediaType;

}


export interface ParentMessageSnippet {
  parentMessageId: number;
  content: string;
  senderDisplayName: string;
  messageType: MediaType;
  media?: string;
}

export enum MessageStatus {
  SENT = 'SENT', DELIVERED = 'DELIVERED', READ = 'READ'
}
export type MediaType = 'TEXT' | 'IMAGE' | 'VIDEO' | 'OTHER';

// ParentMessageSnippet parentMessageSnippet, UserAvatar  , String  ,
//                                   ,MediaType messageType, ) {







