/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserAvatar } from "../../profile/models/ProfileResponseDto";

export interface MessageResponse {
  content?: string;
  sentAt: string;
  messageId: number;
  messageStatus: MessageStatus,
  parentMessageSnippet: ParentMessageSnippet;
  senderAvatar: UserAvatar;
  media: string;
  messageType: MediaType;
  isgab: boolean
}




export interface ParentMessageSnippet {
  parentMessageId: number;
  content: string;
  senderDisplayName: string;
  parentSenderId: number
  messageType: MediaType;
  media?: string;
}

export enum MessageStatus {
  SENT = 'SENT', DELIVERED = 'DELIVERED', READ = 'READ'
}
export type MediaType = 'TEXT' | 'IMAGE' | 'VIDEO' | 'OTHER';

// models/parent-message-with-neighbours.ts

export interface ParentMessageWithNeighbours {
  messages: MessageResponse[];
  gapBefore: GapInfo;
  gapAfter: GapInfo;
}

export interface GapInfo {
  exists: boolean;
  missingCount: number;
  lastMessageId: number;
  lastMessageSentAt: string; // ISO string, map to Date if you prefer
}



