/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MessageResponse {
  content?: string;
  sentAt: string;
  messageId: number;
  senderId: string;
  messageStatus: MessageStatus,
  parentMessageId: number
}




export enum MessageStatus {
  SENT = 'SENT', DELIVERED = 'DELIVERED', READ = 'READ'
}


