/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserAvatar } from "../../models/ProfileResponseDto";

export interface UserResponse {
  userAvatar: UserAvatar;
  profileBio: string;
  isVerified: boolean;
  isFollowedByCurrentUser: boolean;
  isFollowingCurrentUser: boolean;
  canBeMessagedByCurrentUser: boolean;
  canBeAddedToGroupByCurrentUser: boolean;
}

