/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpParams } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { BaseService } from '../../../core/services/base.service';
import { MessageDetailResponse } from '../models/message-detail-response';
import { MessageResponse, ParentMessageWithNeighbours } from '../models/message-response';
import { ScrollDirection } from '@angular/material/tabs';
import { ScrollDirectionCustameType } from '../components/chat-messages/chat-messages.component';
import { UserAvatar } from '../../profile/models/ProfileResponseDto';
import { ChatService } from './chat.service';
import { TimestampSeekRequest } from '../../models/TimestampSeekRequestDto';


@Injectable({ providedIn: 'root' })
export class MessageService extends BaseService {

    constructor(private httpClient: HttpClient, private chatService: ChatService) {
        super()
    }
    sendMessage(
        chatId: string,
        content: string,
        file?: File,
        parentMessageId?: number
    ): Observable<number> {
        const formData = new FormData();

        // JSON part ("request")
        const request = { content };
        formData.append(
            "request",
            new Blob([JSON.stringify(request)], { type: "application/json" })
        );

        // File part (optional)
        if (file) {
            formData.append("attachment", file);
        }

        // Append parentMessageId as query param (only if defined, including 0)
        let url = `${this.baseUrl}${this.ENDPOINTS.chats}${chatId}/sendMessage`;
        if (parentMessageId !== undefined && parentMessageId !== null) {
            url += `?parentMessageId=${parentMessageId}`;
        }

        return this.httpClient.post<number>(url, formData);
    }



    confirmRead(chatId: string) {
        return this.httpClient.post<void>(`${this.baseUrl}${this.ENDPOINTS.chats}${chatId}/confirmRead`, {});
    }


    getMessageInfo(messageId: number): Observable<MessageDetailResponse> {
        return this.httpClient.get<MessageDetailResponse>(
            `${this.baseUrl}${this.ENDPOINTS.messages}${messageId}/info`
        );
    }

    getChatMessages(
        chatId: string,
        scrollDirection: ScrollDirectionCustameType,
        seekRequest?: TimestampSeekRequest,
        missingMessagesCount: number = 10 // allow overriding, default 10
    ): Observable<MessageResponse[]> {
        let params = new HttpParams()
            .set('scrollDirection', scrollDirection)
            .set('missingMessagesCount', missingMessagesCount);

        const url = `${this.baseUrl}${this.ENDPOINTS.chats}${chatId}/chat-messages`;

        // Debug logging
        console.log(`${url}?${params.toString()}`);
        console.log('Request body:', seekRequest ?? {});

        return this.httpClient.post<MessageResponse[]>(
            url,
            seekRequest ?? {}, // empty object if undefined
            { params }
        );
    }

    getGroupMembers(chatId: string): Observable<UserAvatar[]> {
        return this.httpClient.get<UserAvatar[]>(`${this.baseUrl}${this.ENDPOINTS.chats}${chatId}/group-members`);
    }
    getParentMessageWithNeighbours(
        chatId: string,
        messageId: number,
        lastFetchedMessageIdInPage: number
    ): Observable<ParentMessageWithNeighbours> {
        const params = new HttpParams().set('lastFetchedMessageIdInPage', lastFetchedMessageIdInPage);
        return this.httpClient.get<ParentMessageWithNeighbours>(
            `${this.baseUrl}${this.ENDPOINTS.chats}${chatId}/messages/${messageId}`,
            { params }
        );
    }
}
