/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { BaseService } from '../../../core/services/base.service';
import { MessageDetailResponse } from '../models/message-detail-response';
import { MessageResponse } from '../models/message-response';


@Injectable({ providedIn: 'root' })
export class MessageService extends BaseService {

    constructor(private httpClient: HttpClient) {
        super()
    }
    sendMessage(
        chatId: string,
        content: string,
        file?: File,
        parentMessageId?: number
    ): Observable<number> {
        const formData = new FormData();

        // JSON part ("request")
        const request = { content };
        formData.append(
            "request",
            new Blob([JSON.stringify(request)], { type: "application/json" })
        );

        // File part (optional)
        if (file) {
            formData.append("attachment", file);
        }

        // Append parentMessageId as query param (only if defined, including 0)
        let url = `${this.baseUrl}${this.ENDPOINTS.chats}${chatId}/sendMessage`;
        if (parentMessageId !== undefined && parentMessageId !== null) {
            url += `?parentMessageId=${parentMessageId}`;
        }

        return this.httpClient.post<number>(url, formData);
    }

    confirmRead(chatId: string) {
        return this.httpClient.post<void>(`${this.baseUrl}${this.ENDPOINTS.chats}${chatId}/confirmRead`, {});
    }
    getChatMessages(chatId: string): Observable<MessageResponse[]> {
        return this.httpClient.get<MessageResponse[]>(`${this.baseUrl}${this.ENDPOINTS.chats}${chatId}/chat-messages`,)
    }

    getMessageInfo(messageId: number): Observable<MessageDetailResponse> {
        return this.httpClient.get<MessageDetailResponse>(
            `${this.baseUrl}${this.ENDPOINTS.messages}${messageId}/info`
        );
    }
}
