### Create a user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "baraa@gmail.com",
  "username": "baraa",
  "displayName": "Baraa The King",
  "password": "secret12_12",
  "dob": "2002-01-01",
  "gender": "MALE",
  "residence": "Gaza",
  "timezoneId": "Asia/Jerusalem",
  "profilePicture": null,
  "profileCoverPhoto": null,
  "profileBio": "hello, world!"
}

### login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "secret12_12"
}
